### ISSUE TITLE
Allow JSON files with comments

### ISSUE THREAD

**Issue by pradyunsg** [tillig/vscode-json-stable-stringify#2]
This is substantially more difficult as a change but it would be basically awesome to be able to use this in a configuration file or VS Code theme file, without worrying about the comments.

**Comment by tillig** [comment]
You'd need to do a PR or feature request to json-stable-stringify for this one - I use that library, I don't do the sorting myself. Sorry.

**Comment by pradyunsg** [comment]
Thanks for the quick response! :)

This would definitely be out of scope for json-stable-stringify, since it converts a JSON object to a string in a stable manner, instead of round-tripping from string representation to string representation, like this extension.

I guess that means you're saying this is out of scope for this project as well?

**Comment by tillig** [comment]
Correct. The big point of this project was to leverage json-stable-stringify with all its benefits (and drawbacks) to do the work.

**Comment by pradyunsg** [comment]
Cool, thanks for the clarification. :)

---

Thanks for building this extension! It's super helpful as is.

**Comment by TC-Sty** [comment]
Since I not only need a JSON sorter but a converter from JS/TS objects to valid JSON too, I've replaced the built-in JSON parser by the JSON5 parser.

Pros: comments are allowed for input, as well as trailing commas, single-quoted strings, or unquoted identifiers.
Cons: comments aren't preserved for output (that's fine, if you need valid JSON)

If you like to merge the patch, I'll do an PR. (I definitly don't publish my fork to the VSC marketplace because of this: <https://xkcd.com/927/>)

**Comment by tillig** [comment]
I didn't know there was a different parser that could be used. Interesting. I assume the deserialization would effectively just drop all the comments, trailing commas, all that, and then the standard json-stable-stringify would write it out without all that.

Sure, I'd take a PR for that.

**Comment by tillig** [comment]
Just published 1.2.0 with this update. It's going through verification now; should be on the marketplace very soon.
